[project]
name = "komit"
version = "0.5.1"
description = "AI-powered git commit message generator using local LLMs"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "Apache 2.0" }
authors = [
    { name = "Vlad Digori", email = "digorivlad59@gmail.com" }
]
keywords = ["git", "commit", "ai", "llm", "ollama", "developer-tools"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "argcomplete>=3.6.3",
    "httpx>=0.28.1",
    "mypy>=2.1.0",
    "ollama>=0.4.0",
    "pip>=26.1.1",
    "platformdirs>=4.9.6",
    "requests>=2.33.1",
    "rich>=15.0.0",
]

[project.scripts]
komit = "komit.main:run"
komit-update = "komit.update_utils:update_pip"
komit-update-binary = "komit.update_utils:update_binary"
komit-uninstall = "komit.update_utils:uninstall"

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "build>=1.4.4",
    "twine>=6.2.0",
    "pyinstaller>=6.0.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.4.0"
]
[tool.mypy]
python_version = "3.13"
strict = false
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["E","F","I"]
ignore = []


[tool.git-cliff.changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message }}
{% endfor %}
{% endfor %}
"""

[tool.git-cliff.git]
conventional_commits = true
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^chore", group = "Changed" },
    { message = "^docs", group = "Documentation" },
]


[project.urls]
Homepage = "https://github.com/glemiu6/komit"
Repository = "https://github.com/glemiu6/komit"
"Bug Tracker" = "https://github.com/glemiu6/komit/issues"
